[package]
name = "blockchain_init"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10.8"  # For basic hash generation
rand = "0.8"  # For generating random numbers
curve25519-dalek = "4.1.3"  # For elliptic curve operations
bulletproofs = "5.0.0"
merlin = "3.0.0"